gTargets/gTargets/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.context_processors import static

from gTargets import settings


def redirect_to_user(request):
    return HttpResponseRedirect(reverse('user:current_user'))

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^site/', include('sitework.urls', namespace='sitework')),
    url(r'^subscriptions/', include('subscriptions.urls', namespace='subscriptions')),
    url(r'^auth/', include('user_auth.urls', namespace='auth')),
    url(r'^user/', include('user_work.urls', namespace='user')),
    url(r'^$', redirect_to_user),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

gTargets/subscriptions/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'subscriptions.views.index', name="subscriptions"),
    url(r'^subscribe/(?P<user_id>\d+)$', 'subscriptions.views.subscribe', name="subscribe"),
    url(r'^unsubscribe/(?P<user_id>\d+)$', 'subscriptions.views.unsubscribe', name="unsubscribe"),
    url(r'^(?P<user_id>\d+)/$', 'subscriptions.views.user_subscriptions', name="user_subscriptions"),
    url(r'^ajax/subscribe/(?P<user_id>\d+)$', 'subscriptions.views.subscribe_unsubscribe_ajax', name="ajax_subs")
]

gTargets/user_work/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'user_work.views.index', name='current_user'),
    url(r'^(?P<user_id>\d+)$', 'user_work.views.user_profile', name='user_profile'),
    url(r'^load_avatar$', 'user_work.views.load_avatar', name='load_avatar'),
    url(r'^settings/profile$', 'user_work.views.edit_info', name='settings'),
    url(r'^settings/user$', 'user_work.views.edit_info_user', name='settings_user'),
]

gTargets/user_work/models.py
# -*- coding: utf-8 -*-
import os

from django.contrib.auth.models import User
from django.db import models


GENDER_CHOICES = ( #Почему не словарь?
        ('M', 'Male'),#а если пользователь русскоговорящий?
        ('F', 'Female'),
)


def get_path(instance, filename):
    return os.path.join('user', 'avatar', instance.user.username, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    about = models.TextField(blank=True)
    score = models.IntegerField(blank=True, default=0)
    rating = models.IntegerField(blank=True, default=0)
    gender = models.CharField(blank=True, max_length=1, choices=GENDER_CHOICES)
    subscriptions = models.ManyToManyField('Profile', blank=True)
    avatar = models.ImageField(blank=True, upload_to=get_path)

gTargets/user_work/forms.py
from django import forms
from django.contrib.auth.models import User

from user_work.models import Profile


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =["avatar"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar", "gender", "about"]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

gTargets/user_work/views.py
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect as Redirect
from django.shortcuts import render, get_object_or_404

from gTargets import settings
from user_work.forms import AvatarForm, ProfileForm, UserForm
from user_work.models import Profile


@login_required
def index(request):
    return Redirect(reverse('user:user_profile', kwargs={"user_id":request.user.id}))


@login_required
def user_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    profile = get_object_or_404(Profile, user=user)
    profile_current = Profile.objects.get(user=request.user)
    subscriptions = profile_current.subscriptions.all()
    subscribed = profile in subscriptions
    form = AvatarForm()
    return render(request, "user_work/user.html", {"form":form,
                                                   "current_user":request.user,
                                                   "subscribed":subscribed,
                                                   "user":{"user":user,
                                                           "profile":profile}})


@login_required
def load_avatar(request):
    if request.method == 'POST':
        profile = get_object_or_404(Profile, user_id=request.user.id)
        form = AvatarForm(request.POST, request.FILES, instance=profile)
        if form.is_valid:
            if profile.avatar:
                os.remove(os.path.join(settings.BASE_DIR, settings.MEDIA_ROOT,
                                       profile.avatar.name))
            form.save()
    return Redirect(reverse('user:current_user'))


@login_required
def edit_info(request):
    p = get_object_or_404(Profile, user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=p)
        if form.is_valid():
            form.save()
            return Redirect(reverse("user:settings"))
        else:
            return render(request, "user_work/editinfo.html", {"form": form})
    else:
        form = ProfileForm(instance=p)
        return render(request, "user_work/editinfo.html", {"form": form})


@login_required
def edit_info_user(request):
    user = request.user
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return Redirect(reverse("user:settings_user"))
        else:
            return render(request, "user_work/editinfouser.html", {"form": form})
    else:
        form = UserForm(instance=user)
        return render(request, "user_work/editinfouser.html", {"form": form})

gTargets/user_work/templates/user_work/editinfo.html
{% extends "base.html" %}
{% block content %}
    <div class="form-about">
        <img src="{{ form.avatar.value.url }}" alt="Avatar">
        <form action="{% url 'user:settings' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

gTargets/user_work/templates/user_work/editinfouser.html
{% extends "base.html" %}
{% block content %}
    <div class="form-about">
        <form action="{% url 'user:settings_user' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

gTargets/user_work/templates/user_work/user.html
{% extends "base.html" %}
{% load static %}
{% block for_staticfiles %}
<script>
    $(document).ready(function(){
        $("#subs_button").click(function(){
        var result = $.ajax({
            url:"{% url "subscriptions:ajax_subs" user_id=user.user.id%}",
            async: false
        }).responseText;
        $("#subs_button").attr("value", result);
    });
    });

</script>
{% endblock %}
{% block content %}
    <div class="avatar col-md-4">
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="Avatar"/>
        {% else %}
            <img src="" alt="Avatar"/>
        {% endif %}
        {% if current_user.username == user.user.username %}
            <form action="{% url 'user:load_avatar' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="OK">
            </form>
        {% else %}
{#            {% if subscribed %}#}
{#                <a href="{% url 'subscriptions:unsubscribe' user_id=user.user.id %}">Отписка</a>#}
{#            {% else %}#}
{#                <a href="{% url 'subscriptions:subscribe' user_id=user.user.id %}">Подписка</a>#}
{#            {% endif %}#}
            {% if subscribed %}
                <input id="subs_button" type="button" value="Отписка"/>
            {% else %}
                <input id="subs_button" type="button" value="Подписка"/>
            {% endif %}
        {% endif %}
        <a href="{% url 'subscriptions:user_subscriptions' user_id=user.user.id%}">Подписки</a>
    </div>
    <div class="info col-md-4">
        <div class="name">
            {% if user.user.first_name and user.user.last_name %}
                <h3>{{ user.user.first_name }} {{ user.user.last_name }}</h3>
            {% else %}
                <h3>{{ user.user.username}}</h3>
            {% endif %}

            {% if current_user.username == user.user.username %}
                <a href="{% url 'user:settings_user' %}">(ред.)</a>
            {% endif %}
        </div>
        <div class="about">
            {% if current_user == user.user %}
                <p>О себе(<a href="{% url 'user:settings' %}">ред.</a>): {{ user.profile.about }}</p>
            {% else %}
                <p>О себе: {{ user.profile.about }}</p>
            {% endif %}
        </div>
        <div class="targetlists">
            <h2>Списки целей:</h2><br/>
            {% for target_list in user.profile.target_lists %}
                <div class="targetlist">
                    <h5>{{ target_list.title }}</h5>
                    {% for target in target_list %}
                        <p class="done_{{ target.done }}"><a href="">target.title</a></p>
                    {% endfor %}
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}