gTargets/gTargets/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.context_processors import static

from gTargets import settings


def redirect_to_user(request):
    return HttpResponseRedirect(reverse('user:current_user'))

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^site/', include('sitework.urls', namespace='sitework')),
    url(r'^subscriptions/', include('subscriptions.urls', namespace='subscriptions')),
    url(r'^auth/', include('user_auth.urls', namespace='auth')),
    url(r'^user/', include('user_work.urls', namespace='user')),
    url(r'^$', redirect_to_user),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

gTargets/sitework/urls.py
from django.conf.urls import url

from sitework.views import NewsView

urlpatterns = [
    url(r'^(?P<id>\d+)/$', 'sitework.views.get_news_item', name="news_item"),
    url(r'^$', NewsView.as_view(), name="news")
]

gTargets/subscriptions/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'subscriptions.views.index', name="subscriptions"),
    url(r'^subscribe/(?P<user_id>\d+)$', 'subscriptions.views.subscribe', name="subscribe"),
    url(r'^unsubscribe/(?P<user_id>\d+)$', 'subscriptions.views.unsubscribe', name="unsubscribe"),
    url(r'^(?P<user_id>\d+)/$', 'subscriptions.views.user_subscriptions', name="user_subscriptions"),
    url(r'^ajax/subscribe/(?P<user_id>\d+)$', 'subscriptions.views.subscribe_unsubscribe_ajax', name="ajax_subs")
]

gTargets/user_auth/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$','user_auth.views.user_login', name='auth'),
    url(r'^logout$', 'user_auth.views.user_logout', name='logout'),
]

gTargets/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %} gTargets {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.style.css' %}">
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    {% block for_staticfiles %}{% endblock %}
</head>
<body>
    {% block header %}
    <nav class="navbar navbar-inverse navbar-custom">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="">gTargets</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'user:current_user' %}">Профиль</a></li>

                    <li><a href="{% url 'subscriptions:subscriptions' %}">Подписки</a></li>

                    <li><a href="">Новости</a></li>

                    <li><a href="">Цели</a></li>

                    <li><a href="">Поиск</a></li>

                </ul>
            </div>
            <div>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'auth:logout' %}">Exit</a></li>
                </ul>
            </div>
        </div>



    </nav>
    {% endblock %}

    {% block content %} {% endblock %}

    {% block footer %}
        <div class="navbar-fixed-bottom">
            <div class="navbar-inner">
                <div class="container">
                    <footer class="footer">
                            <p class="text-muted pull-left">gTargets, 2015</p>

                            <div class="pull-right">
                                <a href="">О сайте</a>
                                .
                                <a href="{% url "sitework:news" %}">Новости</a>
                                .
                                <a href="">Контакты</a>
                                .
                                <a href="">Популярные цели</a>
                                .
                                <a href="">Помощь</a>
                            </div>


                    </footer>
                </div>
            </div>
        </div>

    {% endblock %}
</body>
</html>